# Generated by Django 2.2.1 on 2019-09-06 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='posting_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 6, 6, 44, 59, 362226), verbose_name='date posted'),
        ),
    ]
