# Generated by Django 2.2.1 on 2019-09-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='posting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posting_title', models.CharField(max_length=50)),
                ('posting_context', models.TextField()),
                ('posting_date', models.DateTimeField(verbose_name='date posted')),
            ],
        ),
    ]
